language: java
install: true

addons:
  sonarcloud:
    organization: "mrinal-bhattacharya-github"
    token:
      secure: $SONAR_TOKEN

jdk:
 - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: gamestore-api-mrinal
